@startuml
skinparam shadowing false
actor Patient as A
participant "Connect Registration App" as CA
participant "Connect API" as API
participant "Integrated Health Care System (IHCS)" as HCP
participant "Authentication service" as AS

A ->CA: index.html
A <-- CA: web page
A ->CA: join()
CA -> A:  loginPlease()
A --> AS: login()
AS --> CA: login
  note right
    At this point
    I have a google token.
    If I have already seen
    the google token with
    a valid pin/token, we
    have a returning user.
  end note
alt email not verified
  CA --> A: email verification link
  note left #f0262d
    I dont know if this
    step is required.
  end note

  A --> AS: verify email
  destroy AS
end


alt No Token & New User
  CA -> A: HealthCareProvider?
  note left
    The user may have a 
    pin. Check the HCP
  end note

  A --> CA: response

  alt HCP sends PINs
    CA -> A: requestPIN
    A --> CA: PIN
    alt valid pin
    CA -> API: requestToken(pin)
    CA <-- API: token
    CA -> API: associateTokenWithGoogleToken()
    CA <-- API: return
    note left
        Now is a "returning User" ....
    end note
    
    else !valid pin
       CA -> HCP: divertUser(pin,token)
       destroy HCP
    end
    
  else HCP does not send pins
    CA -> HCP: divertUserNoPINorToken()
    destroy HCP
  end
else Have Token & New User
  CA -> API: associateTokenWithGoogleToken
  CA <-- API: return
  note left
      Now is a "returning User" ....
  end note
end


alt not consented
  CA --> A: consentform
  A -> CA: consent
  CA -> API: consent()
  CA <-- API: return
end


CA -> A: updateProfile
A --> CA: updateProfile
CA --> API: updateProfile
API --> CA: return

alt IdentityVerification Not Started
    CA --> HCP: CheckIdentity
    HCP --> CA: return
  ...HCP confirms study participant Identity ...
  HCP -> API: confirmParticipant()
end

CA -> A: Questionnaire
A --> CA: results
CA --> API: results

@enduml
